#!/usr/bin/env bash
entrypoints="\
    DISPLAY_CLEAR \
    DISPLAY_HOME \
    DISPLAY_INIT \
    DISPLAY_LEDS \
    DISPLAY_NUM \
    DISPLAY_PUTC \
    DIVIDE32 \
    HEXTODEC \
    MONRDKEY \
    MULT32 \
    ONE_SEC_DELAY \
    VIA_CTS \
"

mkdir -p include
cp src/mem.s include/defines.s 

for sub in $entrypoints; do
    addr=$(grep -e "$sub\$" ../rom/msbasic/msbasic.lbl| awk '{print $2}')
    echo -e "$sub  \t= \$$addr" >> include/defines.s
done

