#!/usr/bin/env bash
entrypoints="\
    DISPLAY_CLEAR \
    DISPLAY_HOME \
    DISPLAY_INIT \
    DISPLAY_LEDS \
    DISPLAY_NUM \
    DISPLAY_PUTC \
    DIVIDE32 \
    HEXTODEC \
    MONRDKEY \
    MULT32 \
    ONE_SEC_DELAY \
    VIA_CTS \
"

> include/defines.s cat <<"EOF"
; RAM address space

; Zero Page
; $00 - $01     ; 2 bytes for the input buffer
; $02           ; 1 byte  for the display
; $0C - $FF     ; MSBASIC usage start

; $0100 - $01FF     stack 

; $0200 - $02FF     unknown 

; $0300 - $03FF     Input buffer for serial line

HEAP                = $0400     ; 256 bytes of general storage area used by ROM

STORAGE             = $0500     ; $0500 - $0FFF General storage area for RAM programs

START               = $1000     ; Good place to put the RAM program

START_ROM           = $8000
EOF

for sub in $entrypoints; do
    addr=$(grep -e "$sub\$" ../rom/msbasic/msbasic.lbl| awk '{print $2}')
    echo -e "$sub  \t= \$$addr" >> include/defines.s
done

