#!/usr/bin/env python

import sys

addr = 0x2000

for line in sys.stdin:
    s = line[:60].split()
    if len(s) > 1:
        print("{0:04X}: ".format(addr),end="")
        addr += 8
        for b in s[1:9]:
            print(b.upper(),end=' ')
        print();

    if len(s) > 8:
        print("{0:04X}: ".format(addr),end="")
        addr += 8
        for b in s[9:17]:
            print(b.upper(),end=' ')
        print();
        
